name: Build
on: [push]
jobs:
  python-install-dependency:
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependecies
        run: pip install -r requirements.txt 


  python-formatting:
     needs: python-install-dependency
     runs-on: ubuntu-latest
     steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install tools
        run: pip install black flake8
      - name: Check formatting
        run: black . --check
      - name: Check style and errors
        run: flake8 . --extend-ignore=E203,E501,W291

  python-testing:
    needs: python-formatting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run pytest
        env:
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: python -m pytest --log-level=DEBUG tests/ -vv